Async request pattern implementation
medizininformatik-initiative/mii-process-report pull request #51
Opened 2024-12-18 12:28 UTC by wetret

resolves #46

2025-03-03 18:24 UTC, hhund requested changes

2025-03-03 18:24 UTC, hhund commented on src/main/java/de/medizininformatik_initiative/process/report/spring/config/FhirClientConfig.java
> +			"medizininformatik-initiativede_reportSend" }, description = "Initial Result polling interval in milliseconds for asynchronous request pattern when executing search bundle requests, the interval w
Is "tenfold" correct?

https://github.com/medizininformatik-initiative/mii-processes-common/blob/0ad23ab4cd2a6b09af359bec32f2cb20bc579c4f/src/main/java/de/medizininformatik_initiative/processes/common/fhir/client/AsyncFhirClientImpl.java#L56

```suggestion
			"medizininformatik-initiativede_reportSend" }, description = "Initial result polling interval in milliseconds for asynchronous request pattern when executing search bundle requests, the interval will double after every check if a result is not ready")
```

2025-03-04 08:36 UTC, wetret commented on src/main/java/de/medizininformatik_initiative/process/report/spring/config/FhirClientConfig.java
> +			"medizininformatik-initiativede_reportSend" }, description = "Initial Result polling interval in milliseconds for asynchronous request pattern when executing search bundle requests, the interval w
Implemented in 2c7ca66

2025-03-21 14:09 UTC, hhund approved these changes

2025-03-21 14:48 UTC, wetret commented
Contents as well part of #53 and will be merged there

2025-03-21 14:48 UTC, closed without merging